thesaurusData = {
    "ATM": "Distributeur automatique de billets, DAB",
    "Abbey": "Abbaye",
    "Accommodation": "H\u00e9bergement",
    "AccommodationProduct": "Produit d'h\u00e9bergement",
    "AccompaniedPractice": "Accompagnement",
    "ActivityProvider": "Prestataire d'activit\u00e9",
    "AdventurePark": "Parc aventure - accrobranche",
    "Airfield": "A\u00e9rodr\u00f4me",
    "Airport": "A\u00e9roport",
    "AlpinePasture": "Alpage",
    "AntiqueAndSecondhandGoodDealer": "Antiquaire et brocanteur",
    "Apartment": "Appartement",
    "Aqueduct": "Aqueduc",
    "ArcheologicalSite": "Site arch\u00e9ologique",
    "Arena": "Ar\u00e8ne",
    "ArtGalleryOrExhibitionGallery": "Galerie d'art, galerie d'exposition",
    "ArtistSigning": "D\u00e9dicace et rencontre d'artiste",
    "Auditorium": "Auditorium",
    "Bakery": "Boulangerie",
    "BalneotherapyCentre": "Centre de baln\u00e9oth\u00e9rapie",
    "BarOrPub": "Bar, bar \u00e0 th\u00e8me",
    "Basilica": "Basilique",
    "Bastide": "Bastide",
    "Beach": "Plage",
    "BeachClub": "Club de plage",
    "Bed": "Lit",
    "BikeStationOrDepot": "Station ou d\u00e9p\u00f4t de v\u00e9lo",
    "BilliardRoom": "Salle de billard",
    "Bishopric": "Ev\u00e9ch\u00e9",
    "BistroOrWineBar": "Bistrot - Bar \u00e0 vin",
    "BoardMeeting": "Conseil d'administration",
    "BoatRestaurant": "Bateau-restaurant",
    "Bocage": "Bocage",
    "Bog": "Tourbi\u00e8re",
    "BoulesPitch": "Boulodrome",
    "BoutiqueOrLocalShop": "Boutique, commerce de proximit\u00e9",
    "BowlingAlley": "Bowling",
    "BrasserieOrTavern": "Brasserie ou taverne",
    "Brewery": "Brasseur",
    "BricABrac": "Brocante",
    "Bridge": "Pont",
    "Bubble": "Bulle",
    "BuddhistTemple": "Temple bouddhique",
    "Bungalow": "Bungalow, Mobil Home",
    "Bungatoile": "Bungatoile",
    "BusStation": "Gare routi\u00e8re",
    "BusStop": "Arr\u00eat, station de transport en commun",
    "BusinessEvent": "Ev\u00e8nement professionnel d'entreprise",
    "BusinessPlace": "Site d'affaires",
    "Cabaret": "Cabaret",
    "CableCarStation": "T\u00e9l\u00e9ph\u00e9rique",
    "CafeOrTeahouse": "Caf\u00e9 ou salon de th\u00e9",
    "Calvary": "Calvaire et enclos paroissiaux",
    "CamperVanArea": "Aire de camping-car",
    "Camping": "Camping",
    "CampingAndCaravanning": "H\u00f4tellerie de plein air",
    "CampingCar": "Camping car",
    "CampingPitch": "Emplacement de camping",
    "Canal": "Canal",
    "Canyon": "Canyon",
    "CarOrBikeWash": "Station de lavage",
    "Caravan": "Caravane",
    "Carnival": "Carnaval",
    "CarpoolArea": "Aire de covoiturage",
    "Casino": "Casino",
    "Castle": "Ch\u00e2teau",
    "CastleAndPrestigeMansion": "Ch\u00e2teau et demeure de prestige",
    "Cathedral": "Cath\u00e9drale",
    "Causse": "Causse",
    "CaveSinkholeOrAven": "Grotte, gouffre, aven, caverne, carri\u00e8re",
    "Cellar": "Cave ou caveau",
    "Chalet": "Chalet",
    "ChalkyLawn": "Pelouse calcaire",
    "ChamberOfCommerceAndIndustry": "Chambre de commerce et d'industrie",
    "Chapel": "Chapelle",
    "Chartreuse": "Chartreuse",
    "ChildrensEvent": "Ev\u00e8nement jeune public",
    "ChildrensGite": "G\u00eete d'enfants",
    "Church": "Eglise",
    "Cinema": "Cin\u00e9ma",
    "Cinematheque": "Cin\u00e9math\u00e8que",
    "CircusPlace": "Cirque",
    "Cirque": "Cirque naturel",
    "Citadel": "Citadelle",
    "CityHeritage": "Ville et village",
    "CivilCemetery": "Cimeti\u00e8re civil",
    "Cliff": "Falaise",
    "ClimbingWall": "Site et mur d'escalade",
    "Cloister": "Clo\u00eetre",
    "ClubOrHolidayVillage": "Club et village vacances",
    "Coastline": "C\u00f4te, littoral",
    "Col": "Col",
    "CollectiveAccommodation": "H\u00e9bergement collectif",
    "CollectiveHostel": "Auberge collective",
    "Collegiate": "Coll\u00e9giale",
    "Commanderie": "Commanderie",
    "Commemoration": "Comm\u00e9moration",
    "Competition": "Comp\u00e9tition",
    "Concert": "Concert",
    "ConeNeck": "C\u00f4ne",
    "Conference": "Conf\u00e9rence",
    "Congress": "Congr\u00e8s",
    "ConvenientService": "Service pratique",
    "Convent": "Couvent",
    "ConventionCentre": "Centre de congr\u00e8s",
    "Cooperative": "Coop\u00e9rative",
    "Course": "Cours",
    "CoveredMarket": "Halle, march\u00e9 couvert",
    "CraftsmanShop": "Artisan d'art",
    "Crest": "Cr\u00eate",
    "CrossCountrySkiResort": "Domaine de ski nordique",
    "CrossCountrySkiTrail": "Piste de ski de fond",
    "Cuesta": "Cuesta",
    "CulturalActivityProvider": "Prestataire d'activit\u00e9 culturelle",
    "CulturalEvent": "\u00c9v\u00e8nement culturel",
    "CulturalSite": "Site culturel",
    "Culture": "Culture",
    "Cybercafe": "Cybercaf\u00e9",
    "CyclingTour": "Itin\u00e9raire cyclable",
    "DefenceSite": "Site de d\u00e9fense",
    "DepartementTourismCommittee": "Comit\u00e9 d\u00e9partemental du tourisme",
    "DepartmentStore": "Grand magasin",
    "DevelopmentCourse": "Stage de perfectionnement",
    "Distillery": "Distillerie",
    "District": "Quartier",
    "DogSleddingTrail": "Piste de chien de traineau",
    "DownhillSkiResort": "Domaine de ski alpin",
    "DownhillSkiRun": "Piste de ski alpin",
    "Dune": "Dune",
    "Dungeon": "Donjon",
    "EducationalTrail": "Sentier de d\u00e9couverte et d'interpr\u00e9tation",
    "ElectricBycicleChargingPoint": "Borne de charge \u00e9lectrique pour v\u00e9lo, vtt",
    "ElectricVehicleChargingPoint": "Borne de charge v\u00e9hicule \u00e9lectrique",
    "EntertainmentAndEvent": "F\u00eate et manifestation",
    "EquestrianCenter": "Centre \u00e9questre",
    "EquipmentRental": "Location de mat\u00e9riel",
    "EquipmentRentalShop": "Loueur de mat\u00e9riel",
    "EquipmentRepairShop": "R\u00e9parateur de mat\u00e9riel",
    "ExecutiveBoardMeeting": "Bureau \u00e9x\u00e9cutif",
    "Exhibition": "Exposition",
    "FairOrShow": "Foire ou salon",
    "Farm": "Ferme",
    "FarmCamping": "Camping \u00e0 la ferme",
    "Farmer": "\u00c9leveur",
    "FarmhouseInn": "Ferme et auberge de campagne",
    "FastFoodRestaurant": "Restauration Rapide",
    "Festival": "Festival",
    "FirstPractice": "Bapt\u00eame sportif",
    "FitnessCenter": "Centre de remise en forme - fitness",
    "FitnessPath": "Parcours de Sant\u00e9",
    "FluvialTour": "Itin\u00e9raire fluvial ou maritime",
    "FoodEstablishment": "Restauration",
    "Forest": "For\u00eat",
    "Forge": "Forge",
    "Fort": "Fort",
    "FortifiedCastle": "Ch\u00e2teau fort",
    "FortifiedSet": "Ensemble fortifi\u00e9",
    "Fountain": "Fontaine",
    "FreePractice": "Pratique libre",
    "FrontonBelotaCourt": "Fronton, mur de frappe",
    "Game": "Jeu, concours",
    "GarageOrAirPump": "Borne ou station de r\u00e9paration - gonflage",
    "GarageSale": "Vide-grenier",
    "Glacier": "Glacier de montagne",
    "GolfCourse": "Terrain de golf",
    "Gorge": "Gorge",
    "GourmetRestaurant": "Restaurant gastronomique",
    "Grassland": "Prairie",
    "GroupLodging": "G\u00eete de groupe",
    "Guesthouse": "Chambre d'h\u00f4tes",
    "Gymnasium": "Salle ou terrain de sport, gymnase",
    "HalophilicArea": "Zone halophile",
    "Hammam": "Hammam",
    "Harvest": "Vendange, r\u00e9colte",
    "HealthcarePlace": "Lieu de soins",
    "HealthcareProfessional": "Professionnel de sant\u00e9",
    "Hillsides": "C\u00f4teau",
    "HolidayCentre": "Centre de vacances et de loisirs",
    "HolidayResort": "R\u00e9sidence de tourisme",
    "HorseTour": "Itin\u00e9raire \u00e9questre",
    "Hotel": "H\u00f4tel",
    "HotelRestaurant": "H\u00f4tel-restaurant",
    "HotelSuite": "Suite",
    "HotelTrade": "H\u00f4tellerie",
    "House": "Maison",
    "HouseBoat": "B\u00e2teau habitable",
    "Hut": "Cabane",
    "HypermarketAndSupermarket": "Grande et moyenne surface",
    "IceCreamShop": "Glacier",
    "IceSkatingRink": "Patinoire",
    "Icefall": "Cascade de glace",
    "IncomingTravelAgency": "Organisme r\u00e9ceptif",
    "IndustrialSite": "Site industriel",
    "InterpretationCentre": "Centre d'interpr\u00e9tation",
    "IntroductionCourse": "Stage d'initiation",
    "IslandPeninsula": "Ile - presqu'\u00eele",
    "Jetty": "Embarcad\u00e8re",
    "KidsClub": "Club enfants",
    "Lake": "Lac",
    "Landes": "Landes",
    "LaunchingRamp": "Rampe de mise \u00e0 l'eau",
    "LeftLuggage": "Consigne \u00e0 bagages",
    "LeisureChalet": "Chalet r\u00e9sidentiel de loisirs",
    "LeisureComplex": "Complexe de loisirs (loisirs regroup\u00e9s)",
    "LeisureSportActivityProvider": "Prestataire d'activit\u00e9 sportive et de loisir",
    "LevyOrDike": "Barrage, digue",
    "Library": "Biblioth\u00e8que - M\u00e9diath\u00e8que",
    "Lighthouse": "Phare",
    "LocalAnimation": "Animation locale",
    "LocalProductsShop": "Maison de pays, produits du terroir",
    "LocalTouristOffice": "Office de tourisme",
    "Lock": "Ecluse",
    "Marina": "Port de plaisance",
    "Market": "March\u00e9",
    "MedicalPlace": "Lieu de sant\u00e9",
    "MegalithDolmenMenhir": "M\u00e9galithes, menhirs et dolmens",
    "MilitaryCemetery": "Cimeti\u00e8re militaire et m\u00e9morial",
    "Mill": "Moulin",
    "Mine": "Mine",
    "MiniGolf": "Mini golf",
    "Monastery": "Monast\u00e8re, prieur\u00e9",
    "MooringArea": "Zone ou port de mouillage",
    "Mosque": "Mosqu\u00e9e",
    "Mountain": "Montagne",
    "MountainResort": "Station de montagne",
    "MountainRestaurant": "Restaurant d'altitude / Restaurant d'alpage",
    "MultiActivity": "Multiactivit\u00e9s",
    "MultiPurposeRoomOrCommunityRoom": "Salle polyvalente, salle des f\u00eates",
    "Museum": "Mus\u00e9e",
    "NaturalCampingArea": "Aire naturelle de camping",
    "NaturalCuriosity": "Curiosit\u00e9 naturelle",
    "NaturalHeritage": "Site naturel",
    "NaturalPark": "Parc naturel",
    "NauticalCentre": "Base nautique / centre nautique",
    "NightClub": "Discoth\u00e8que",
    "NonHousingRealEstateRental": "Location de salle",
    "OpenDay": "Portes ouvertes",
    "Opera": "Op\u00e9ra (spectacle)",
    "OperaHouse": "Op\u00e9ra (salle)",
    "Orchard": "Verger conservatoire",
    "OutstandingTree": "Arbre remarquable",
    "Palace": "Palais",
    "Parade": "D\u00e9fil\u00e9 Cort\u00e8ge Parade",
    "ParkAndGarden": "Parc et jardin",
    "Parking": "Parking",
    "Peak": "Pic",
    "Pharmacy": "Pharmacie",
    "PicnicArea": "Aire de pique-nique",
    "Pier": "Jet\u00e9e",
    "PigeonLoft": "Pigeonnier",
    "PilgrimageAndProcession": "P\u00e8lerinage et procession",
    "PlaceOfInterest": "Lieu",
    "Plain": "Plaine",
    "Plateau": "Plateau",
    "PlayArea": "Aire de jeux",
    "PointOfInterest": "Point d'int\u00e9r\u00eat",
    "PointOfView": "Point de vue",
    "Pond": "Etang",
    "Practice": "Pratique",
    "Producer": "Producteur",
    "ProducersGroup": "Groupement de producteurs",
    "Product": "Produit",
    "ProfessionalTourGuide": "Guide professionnel",
    "PublicLavatories": "Toilettes publiques",
    "RVServiceArea": "Borne de service camping car",
    "Racetrack": "Hippodrome",
    "RacingCircuit": "Circuit automobile ou moto",
    "RailBike": "V\u00e9lorail",
    "Rally": "Rallye",
    "Rambling": "Randonn\u00e9e, balade",
    "Reading": "Lecture",
    "Recital": "R\u00e9cital",
    "RegionalTourismCommittee": "Comit\u00e9 r\u00e9gional du tourisme",
    "ReligiousEvent": "\u00c9v\u00e8nement religieux",
    "ReligiousSite": "Site religieux",
    "RemarkableBuilding": "B\u00e2timent civil remarquable",
    "RemarkableHouse": "Maison remarquable",
    "RemembranceSite": "Lieu de m\u00e9moire",
    "Rental": "Location",
    "RentalAccommodation": "H\u00e9bergement locatif",
    "ResidentialLeisurePark": "Parc r\u00e9sidentiel de loisirs",
    "RestStop": "Halte de repos",
    "Restaurant": "Restaurant",
    "River": "Rivi\u00e8re ou fleuve",
    "RiverPort": "Halte et port fluvial",
    "RoadTour": "Itin\u00e9raire routier",
    "RomanPath": "Voie romaine",
    "Room": "Chambre",
    "Ruins": "Ruines et vestiges",
    "SaleEvent": "Ev\u00e8nement commercial",
    "SchoolOrTrainingCentre": "Ecole et centre d'apprentissage",
    "ScreeningEvent": "Projection, cin\u00e9ma",
    "Seaport": "Port maritime",
    "SelfCateringAccommodation": "Meubl\u00e9s de tourisme",
    "SelfServiceCafeteria": "Caf\u00e9t\u00e9ria - Self",
    "Seminar": "S\u00e9minaire",
    "ServiceArea": "Aire de service",
    "ServiceProvider": "Prestataire de service",
    "ShoppingCentreAndGallery": "Centre et galerie commerciale",
    "ShowEvent": "Spectacle",
    "SightseeingBoat": "Bateau promenade",
    "SmallCulturalHeritage": "Petit patrimoine culturel",
    "SocialEvent": "Ev\u00e8nement social",
    "Source": "Source",
    "Spa": "Etablissement thermal",
    "SpaResort": "Station thermale",
    "SportsAndLeisurePlace": "Site sportif, r\u00e9cr\u00e9atif et de loisirs",
    "SportsClub": "Club de sport",
    "SportsCompetition": "Comp\u00e9tition sportive",
    "SportsDemonstration": "D\u00e9monstration sportive",
    "SportsEvent": "\u00c9v\u00e8nement sports et loisirs",
    "SportsHall": "Palais des sports",
    "SquashCourt": "Salle de squash",
    "Stables": "Haras",
    "Stadium": "Stade",
    "Stone": "Pierre, rocher",
    "StopOverOrGroupLodge": "Refuge et g\u00eete d'\u00e9tape",
    "Store": "Commerce de d\u00e9tail",
    "Stream": "Ruisseau",
    "StreetFood": "Restauration ambulante, Food truck",
    "StubbleFields": "Chaumes",
    "SummerToboggan": "Piste de luge d'\u00e9t\u00e9",
    "Summit": "Sommet",
    "Swamp": "Marais",
    "SwimmingPool": "Piscine",
    "Synagogue": "Synagogue",
    "TableHoteGuesthouse": "Chambre et table d'h\u00f4tes",
    "TableHotes": "Table d'h\u00f4tes",
    "Tasting": "D\u00e9gustation",
    "TastingProvider": "Fournisseur de d\u00e9gustation",
    "TaxiCompany": "Compagnie de taxis",
    "TaxiStation": "Aire, station de taxis",
    "TeachingFarm": "Ferme p\u00e9dagogique",
    "TechnicalHeritage": "Patrimoine industriel, artisanal, rural, agricole et technique",
    "Temple": "Temple",
    "TennisComplex": "Compl\u00e8xe ou terrain de tennis",
    "Tent": "Tente",
    "TerrainPark": "Snowpark",
    "ThalassotherapyCentre": "Centre de thalassoth\u00e9rapie",
    "Theater": "Th\u00e9atre, Salle de spectacle",
    "TheaterEvent": "Pi\u00e8ce de th\u00e9\u00e2tre",
    "ThemePark": "Parc de loisirs, parc \u00e0 th\u00e8me",
    "Tipi": "Tipi",
    "TobogganBobsleigh": "Piste de luge / bobsleigh",
    "Tour": "Itin\u00e9raire touristique",
    "TourGuideAgency": "Agence de guides",
    "TourOperatorOrTravelAgency": "Voyagiste",
    "TourismCableCar": "T\u00e9l\u00e9ph\u00e9rique touristique",
    "TourismCentre": "Maison du tourisme",
    "TouristBus": "Bus touristique",
    "TouristInformationCenter": "Service d'information touristique",
    "TouristTrain": "Train touristique",
    "Tower": "Tour",
    "TrackRollerOrSkateBoard": "Piste de roller ou de skate board",
    "Trader": "N\u00e9gociant",
    "TraditionalCelebration": "F\u00eate traditionnelle",
    "TrainStation": "Gare ferroviaire",
    "Traineeship": "Stage, atelier",
    "TrainingWorkshop": "Atelier de formation",
    "Trampoline": "Tremplin",
    "Transport": "Transport",
    "Transporter": "Transporteur",
    "TreeHouse": "Cabane dans les arbres",
    "TriumphalArch": "Arc de triomphe",
    "UnderwaterRoute": "Itin\u00e9raire sous-marin",
    "Valley": "Vall\u00e9e",
    "Velodrome": "V\u00e9lodrome",
    "ViaFerrata": "Via ferrata",
    "Visit": "Visite",
    "VisualArtsEvent": "Son et lumi\u00e8re, feu d'artifice",
    "VivariumAquarium": "Vivarium - Aquarium",
    "Volcano": "Volcan",
    "VolunteerTourGuideOrGreeter": "H\u00f4te b\u00e9n\u00e9vole, greeter",
    "WalkingTour": "Itin\u00e9raire p\u00e9destre",
    "WashHouse": "Lavoir",
    "WaterSource": "Point d'eau",
    "Waterfall": "Cascade",
    "Wetland": "Zone humide",
    "WifiHotSpot": "Hotspot Wifi",
    "WorkMeeting": "R\u00e9union de travail",
    "YachtClub": "Yacht Club",
    "YouthHostelAndInternationalCenter": "Auberge de jeunesse et centre international de s\u00e9jour",
    "Yurt": "Yourte",
    "ZooAnimalPark": "Zoo - parc animalier"
}

thesaurusDataToExclude = {
    "PointOfInterest",
    "PlaceOfInterest",
    "Product",
    "Restaurant"
}